### PR TITLE
Improvements to OCP docs plain text generation:

### PR DESCRIPTION
**Pull request by syedriko**
Improvements to OCP docs plain text generation:

- Brought attributes from openshift-docs/blob/enterprise-4.15/_attributes/common-attributes.adoc
- Removed surrounding double quotes from attribute values in the generated plaintext
- Added handling of (R) (registered trademark) sign
- "bad nodes" are now "nodes without whitespace" during embeddings generation

### CODE REVIEW

**Comment by bparees** [comment]
@syedriko will the failures(unreachable urls here be resolved by the docs update in #28 ?

also it would be nice if `skipping bad node` indicated why the node was considered bad

**Comment by syedriko** [comment]
> @syedriko will the failures(unreachable urls here be resolved by the docs update in #28 ?

yep

> also it would be nice if `skipping bad node` indicated why the node was considered bad

Will be saying "skipping node without whitespace"

**Comment by syedriko** [comment]
@bparees PTAL

**Pull request merged**
