### PR TITLE
OLS-1271: Add project and org to the Konflux Snyk task

### PR DESCRIPTION
**Pull request by syedriko**
Add project and org to the Konflux Snyk task so Snyk scan results are sent to snyk.io.

### CODE REVIEW

**Comment by syedriko** [comment]
/approve
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-rag-content"
/override "Red Hat Konflux / ols-enterprise-contract / pr group syedriko-ols-1271"

**Comment by tisnik** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-rag-content"

**Comment by tisnik** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-rag-content"

**Pull request merged**
